version: "3.9"
services:
    pricer:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
          - "50051:50051"
        command: ["/work/htask/build/pricer"]
        healthcheck:
            test: ["CMD-SHELL", "bash -c '</dev/tcp/localhost/50051'"]
            interval: 2s
            timeout: 2s
            retries: 5
            start_period: 2s

    get_bba:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["/work/htask/build/consumer", "--host", "pricer"]
        depends_on:
            pricer:
                condition: service_healthy

    get_vbd:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["/work/htask/build/consumer", "--host", "pricer", "--topic", "vbd"]
        depends_on:
            pricer:
                condition: service_healthy

    get_pbd:
        build:
            context: .
            dockerfile: Dockerfile
        command: ["/work/htask/build/consumer", "--host", "pricer", "--topic", "pbd"]
        depends_on:
            pricer:
                condition: service_healthy
